### ISSUE TITLE
Add sample script

### ISSUE THREAD

**Issue by MichaelCurrin** [daz4126/Nanny-State#4]
e.g.

In the repo put

- `examples`
  - `basic`
    - `package.json` (installing from NPM)
    - `index.js`

So someone can run the code in that directory or copy it to their own project.

**Comment by MichaelCurrin** [comment]
Maybe in addition to CodePen, you can have a browser example too.

so in `examples/browser` you can have `index.html` which uses ES Modules to load from the CDN and do a hello world. It doesn't need CSS etc. Just get it to run and have someone run it locally such as with VS Code Live Server. 

You can even set the page to run on GitHub Pages so you have a demo site outside CodePen that uses the latest NPM package - then you can check your demo page whenever you make a release, to ensure it works locally and/or on the remote.

**Comment by MichaelCurrin** [comment]
I tried to make a Node script but it fails because of lack of `window`.

`index.mjs`
```js
import { Nanny, html } from "nanny-state";

const State = { name: "World" }
Nanny(State)
```

```console
$ node index.mjs
file:///Users/mcurrin/Temp/nanny/node_modules/lit-html/lib/template-result.js:27
const policy = window.trustedTypes &&
               ^

ReferenceError: window is not defined
    at file:///Users/mcurrin/Temp/nanny/node_modules/lit-html/lib/template-result.js:27:16
```

**Comment by daz-codes** [comment]
I've added a browser example and you can also see it on github pages here https://daz4126.github.io/Nanny-State/examples/counter/

**Comment by daz-codes** [comment]
I'm not convinced about adding an example using npm. I will probably create a template on CodeSandbox that people can fork and use to build in the browser without having to install npm.

**Comment by daz-codes** [comment]
Here is the Nanny State template on CodeSandBox:
https://codesandbox.io/s/nanny-state-x6yh0
