### ISSUE TITLE
Using eventHandler in State

### ISSUE THREAD

**Issue by thipages** [daz4126/Nanny-State#7]
Hi,
Since this is not in the documentation, declaring events by adding eventHandler function in the State can be useful too.

With the Hello Batman example it goes like this - [see codepen](https://codepen.io/thipages/pen/wveGrWa)
```javascript
import { Nanny,html } from 'https://cdn.skypack.dev/nanny-state';
//
const view = state => 
  html`<h1>Hello ${state.name}</h1>
       <button onclick=${state}>I'm Batman</button>`;
const State = { name: 'Bruce Wayne', view, handleEvent:e=>Update(nameToBatman) }
const nameToBatman = state => ({ name: 'Batman'});
//
const Update = Nanny(State);
```

**Comment by daz-codes** [comment]
This is brilliant! Thanks for sharing. I didn't even know that you could use handleEvent as a default event handler in an object. I'll definitely add this to the docs. It's also got me thinking about the idea of storing all the event handlers and transformer functions in the State object and how this could be used to create self-contained components.

**Comment by thipages** [comment]
Hi,
yes js is a cool.
About self-contained components, Nanny could remove the current Update reference, adding on the fly  a new "update" function

```javascript
import { Nanny,html } from 'https://cdn.skypack.dev/nanny-state';
//
const view = state => 
  html`<h1>Hello ${state.name}</h1>
       <button onclick=${state}>I'm Batman</button>`;
const State = { name: 'Bruce Wayne', view, handleEvent:function (e) {this.update(nameToBatman); }
const nameToBatman = state => ({ name: 'Batman'});
//
Nanny(State);
```

**Comment by thipages** [comment]
It could be also  interesting to design inter-components communication (no idea yet)
